### PR TITLE
update ruby versions

### PR DESCRIPTION
**Pull request by icorson3**
Update with latest ruby versions 2.4, 2.5, 2.6

cc: @zendesk/classic-upgrade

### CODE REVIEW

**Comment by grosser** [comment]
are we even using this ?
... I think this is just a fork and the main repo needs the update

**Comment by icorson3** [comment]
@grosser classic is using `gem "mail", git: 'https://github.com/zendesk/mail', ref: '261-as-259'` but we would like to use the main repo, there is a PR in for classic to see if we can do so here: https://github.com/zendesk/zendesk/pull/39319 that is currently failing

**Comment by grosser** [comment]
then should merge that into 261-as-259 and not master ?

**Review by grosser — APPROVED** [review]

**Comment by alduethadyn** [comment]
Are we going to ditch this? Or fix tests?

**Comment by icorson3** [comment]
I believe we can close this entirely since we moved off the fork @vanchi-zendesk

**Pull request closed without merging**
